language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover

after_success:
    - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover clover; fi



